# Generated by Django 5.2.4 on 2025-07-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pen', 'Pens'), ('notebook', 'Notebooks'), ('game', 'Games'), ('cool_Items', 'Cool Items'), ('color', 'Colors')], max_length=50),
        ),
    ]
