# Generated by Django 5.2.4 on 2025-07-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('all', 'All Categories'), ('pen', 'Pens'), ('notebook', 'Notebooks'), ('game', 'Games'), ('cool_Items', 'Cool Items'), ('color', 'Colors')], default='all', max_length=50),
        ),
    ]
